spring:
  application:
    name: todo-api
  datasource:
    url: jdbc:postgresql://localhost:5432/todo_api
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8085
token:
  signing:
    key: H8suM7pH+vTcYdcS3bf3Z6XZ2PO5w/9Pz0U4RgLvEKc=